# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self
- repository: devops-pipeline-templates
  type: git
  name: devops-pipeline-templates

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'sc-rooai-aios-dev-gwc-001'
  imageRepository: 'astk-backend'
  imageRepositoryUi: 'astk-ui'
  containerRegistry: 'crrooaiaiosdevgwc001.azurecr.io'
  tag: '$(Build.BuildNumber)'
  dockerFilePath: $(Build.SourcesDirectory)/docker/Dockerfile.backend
  dockerFilePathUi: $(Build.SourcesDirectory)/docker/Dockerfile.app
  # Agent VM image name
  poolName: 'pool-vla-001'



stages:
- stage: BuildAndPush
  displayName: Build and push stage
  jobs:
  - job: BuildAndPushBackend
    displayName: Build and push backend
    pool: $(poolName)
    steps:
    - template: build_and_push_docker.yml@devops-pipeline-templates
      parameters: 
        dockerRegistryServiceConnection: $(dockerRegistryServiceConnection)
        imageRepository: $(imageRepository)
        containerRegistry: $(containerRegistry)
        tag: $(tag)
        dockerImageName: $(imageRepository)
        dockerFilePath: $(dockerFilePath)
  - job: BuildAndPushFrontend
    displayName: Build and push frontend
    pool: $(poolName)
    steps:
    - template: build_and_push_docker.yml@devops-pipeline-templates
      parameters: 
        dockerRegistryServiceConnection: $(dockerRegistryServiceConnection)
        imageRepository: $(imageRepositoryUi)
        containerRegistry: $(containerRegistry)
        tag: $(tag)
        dockerImageName: $(imageRepositoryUi)
        dockerFilePath: $(dockerFilePathUi)

- stage: Cleanup
  displayName: Cleanup Job Runner
  dependsOn: BuildAndPush
  jobs:
  - job: Cleanup
    displayName: Cleanup
    pool: $(poolName)
    steps:
    - template: cleanup_private_build_server.yml@devops-pipeline-templates