# https://taskfile.dev

version: '3'
dotenv: ['.env']

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  
  init:
    cmds:
      - uv sync --frozen
      - source .venv/bin/activate
  
  run:
    cmds:
      - uv run src/run_service.py
  
  # INFO: there will be commands for each new Frontend-Component.
  run-sc:
    cmds:
      - uv run src/theme_selector.py --app Skill_Companion --variant {{ .VARIANT | default "default" }}
      - uv run streamlit run src/Skill_Companion.py

  dev:
    desc: "Run Ruff for code quality and formatting"
    cmds:
      - uv run ruff check . --fix
      - uv run ruff format .

  

  

