FROM python:3.12.3-slim

WORKDIR /app

COPY pyproject.toml .
RUN pip install --no-cache-dir uv
RUN uv pip install --system --no-cache -r pyproject.toml

COPY src/agent/ ./agent/
COPY src/schema/ ./schema/
COPY src/service/ ./service/
COPY src/run_service.py .

CMD ["python", "run_service.py"]
