name: Run pre-commit hooks

on:
  pull_request:
    types: [ opened, synchronize ]
    branches: [ main, development ]  # update later to remove development

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    name: Run pre-commit hooks
    steps:
    - uses: actions/checkout@v4

    - name: Install poetry
      run: python -m pip install poetry==1.5.1

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'poetry'
    - name: Install dependencies
      run: poetry install --with dev

    - name: Set up hooks
      run: poetry run pre-commit install

    - name: Run pre-commit hooks
      run: poetry run pre-commit run --all-files
