name: Test Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:

permissions:
  contents: read

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build service image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          tags: agent-service-toolkit.service:${{ github.sha }}
          file: docker/Dockerfile.service

      - name: Build app image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          tags: agent-service-toolkit.app:${{ github.sha }}
          file: docker/Dockerfile.app
