name: Run unit tests

on:
  pull_request:
    types: [ opened, synchronize ]
    branches: [ main, development ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    name: Run unit tests
    steps:
      - uses: actions/checkout@v4

      - name: Install poetry
        run: python -m pip install poetry==1.5.1

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'poetry'

      - name: Install dependencies
        run: poetry install --with dev

      - name: Test with pytest
        run: |
          poetry run pytest --cov-report=xml:test-coverage.xml

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: test-coverage
          path: "test-coverage.xml"

  coverage:
    runs-on: ubuntu-latest
    name: Get unit test coverage
    needs: unit-tests
    permissions: write-all
    steps:
      - uses: actions/download-artifact@v4
      - name: Get Coverage
        uses: orgoro/coverage@v3.1
        with:
          coverageFile: "test-coverage/test-coverage.xml"
          token: ${{ secrets.GITHUB_TOKEN }}
          thresholdNew: 0.5
          thresholdAll: 0.9
